language: ruby
rbenv:
- 2.5.3
before_install:
- gem install bundler
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: YUy80coGjQzfdhQyEc7RR+i0H87CuYvPjr/liZtPWeFGMc7fkIyomaPEycJQY4/7zXMeVkc2/GQPtD5ZEoMhXrn2fa/dK5U/7Zmk7H7ijtgWvFhZmsy9ZpETU7f2nWA+dV2CMfuY2VRF+R5RxnR++zH+ySHmdz4L+hIvkPN2CCckJcG5+k+HERbV5F8K96S0no1vAV3C/ME0ZSG/YhRdiIkAYWY371U/v/NO2K/JMOYkV6wKwtiu6ecVm8P1fOteMrY4rLuHrm45G7aEqc/j15gX7r+fzQ7B3EU6GOrJorQCZ8mHIj0diOLsWGLbIx7ikLjWGqsIFk4EY4F7jlSxzG99YwQyIYmUVsqrZLfwu615fNAuuU0m9xbP+yzzCVYRLT3bRBpvahhea/9nMtLTmv78jJRz5HhxNb4XLE7qoA3xNbRZChX1wYOnNrA5YDtiya6VnWubrWFfacD9Apq8GvDs5HI/jO0ngrV3MGTL3rYuuNdIdnuUdCv1Sdcd9JepAqAYQFpQ2p3UxUWnp9Sa4hJvaC7aFzU+tErmCBidnFHyZ+RX/oOo+b1+PSfz0NTu2yqKS08O4vpXKEqNsCYvruvlp09KW6vaSqchCaEpcMwSK9X62d9jolGERf6kBmumzQtU0z2Qib+9ItBTNsJOZjxWIOmm2aiiI3+Q0Eo1hIc=
  app: gtfo-weather-api
  on:
    repo: GetThatFlightOut/Weather-API
    branch: main
env:
  global:
    secure: WWoeeiJ1I5nyq7dYNwn4MGg3lZYe6/EfpviTEdz7eEY3S8vwJGnK8tXUdbLqPpHgGfoG0ftx8Fhn6lJb+Clrcsx6tLMgOXOQ0KyBzdpQA72/jvZnz0C5z3JScKOxMntuNegjbQAd8XUOdmXdbRulph3GAPEG9hVWqrq0PqXP15PhDww935M0pBA+ZyNtat7t90Gj7nmVKy/PO2VcSoEFt2kzkojh2+h0w5fhX9duqZP34A6yC75k7L0bnqE/QK+JlrVLmXoTcRC8E5+vppl/3UGBW5HPyE5KBdDLOd+E/3h0DFNdZIvbOWiUPnD4BfBh2JO4eg6fXqLWoOJD9R47W03WHQa3cBzjNo2PzRVD0D248v8x0XX9ggN4fUEIPMbL/7URoORlCW5GAqmQasXIVa7MfCS4Glv6f5NDRxnHg22kXAmSjBEfI4hjO64BRrEUm2jCS6Nzi3f3uJjqB8mt5ry00fYzeNixAkL6F7tasPuBajvpMq79RfH6pEsU08XxonBG1BKz3S2bQNthgUFXMMU8u85GNV+hdjACUBujmjZYbAIGU+T035ccsq9CHF6nI6OdFLacHeIYUa90OJMCWMhp9EYT/n1dwHjf+ASUkS3h8Jn+ZhCeyw6V29C8DsF1YK8xcjTDT0a3jpCMBcwWPHNXm+VNrPwwPGNX76W2y2Y=
